kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: polaris-route
  namespace: polaris
  labels:
    app: polaris
spec:
  to:
    kind: Service
    name: polaris-dashboard
    weight: 100
  port:
    targetPort: http-dashboard
  wildcardPolicy: None

